// <auto-generated />
using FurniSpace.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FurniSpace.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802100000_CustomizationMultiVersionModel")]
    partial class CustomizationMultiVersionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
