namespace FurniSpace.Application.Common.Notifications;

public enum NotificationType
{
    ProjectRequestSubmitted,
    ProjectRequestAccepted,
    ProjectMoreInformationRequested,
    ProjectBasicInformationUpdated,
    ProjectStatusChanged,
    ProjectRequestRejected,
    ProjectDesignerAssigned,
    ProposalPublished,
    ProposalRevisionRequested,
    ProposalFinalSelected,
    QuotationSent,
    QuotationAccepted,
    QuotationRevisionRequested,
    QuotationRejected,
    CustomizationRequestSubmitted,
    CustomizationDesignerReviewed,
    ProjectFileUploaded,
    ProjectScheduleCreated,
    ProjectScheduleUpdated,
    ProjectScheduleConfirmed,
    ProjectScheduleCompleted,
    ProjectScheduleCancelled,
    OrderDepositPaid,
    PaymentCreated,
    PaymentProcessing,
    PaymentPaid,
    PaymentExpired,
    PaymentCancelled,
    PaymentTransactionFailed,
    PaymentTransactionCancelled,
    ProductionRequestAssigned,
    ProductionItemCancelled
}
