namespace FurniSpace.Domain.Enums;

public enum FileType
{
    SPACE_IMAGE,
    FLOOR_PLAN,
    REFERENCE_IMAGE,
    BRAND_ASSET,
    CAD_FILE,
    PDF_DRAWING,
    MEASUREMENT_REPORT,
    LIDAR_SCAN,
    MODEL_3D,
    TEXTURE,
    PREVIEW,
    PRODUCT_PREVIEW,
    PROPOSAL_PREVIEW,
    PROPOSAL_FILE,
    QUOTATION_FILE,
    ORDER_DOCUMENT,
    PRODUCTION_FILE,
    DELIVERY_PHOTO,
    DELIVERY_NOTE,
    REVIEW_IMAGE,
    PORTFOLIO_IMAGE,
    OTHER
}
