namespace FurniSpace.Domain.Enums;

public enum OrderStatus
{
    CREATED,
    DEPOSIT_PENDING,
    DEPOSIT_PAID,
    IN_PRODUCTION,
    PRODUCTION_PARTIALLY_FAILED,
    PRODUCTION_COMPLETED,
    READY_FOR_DELIVERY,
    DELIVERY_SCHEDULED,
    DELIVERING,
    DELIVERED,
    FINAL_PAYMENT_PENDING,
    COMPLETED,
    CANCELLED
}
