namespace FurniSpace.Domain.Enums;

public enum ProjectStatus
{
    SUBMITTED,
    IN_CONSULTATION,
    NEED_BASIC_INFORMATION,
    WAITING_FOR_DESIGNER_ASSIGNMENT,
    MEASUREMENT_REQUIRED,
    SPACE_VERIFIED,
    PROPOSAL_CONSULTING,
    PROPOSAL_SELECTED,
    QUOTATION_SENT,
    QUOTATION_REVISION_REQUESTED,
    ORDER_CONFIRMED,
    IN_PRODUCTION,
    READY_FOR_DELIVERY,
    DELIVERING,
    DELIVERED,
    COMPLETED,
    REJECTED
}
